theme: jekyll-theme-minimal
title: The Thetford Society
description: The Thetford Society is established for the public – to promote high standards of planning and architecture, to educate the public in the geography, history, natural history and architecture of Thetford and its environs and to secure the preservation, protection, development and improvement of features of historic or public interest.
logo: images/TS Logo clean.png
